-- Reconcile schema drift between migration history and prisma/schema.prisma.
-- Generated by hand from `prisma migrate diff --from-migrations --to-schema-datamodel`,
-- adapted to preserve live data:
--   * courses.price is RENAMED to courses.priceARS (keeps existing pricing) rather than dropped.
--   * courses.priceAUD is added with a DEFAULT 0 so the NOT NULL column applies on non-empty tables.
--   * lessons.description is added.
--   * attachments table is created (schema model had no matching migration).

-- AlterTable
ALTER TABLE "courses" RENAME COLUMN "price" TO "priceARS";
ALTER TABLE "courses" ADD COLUMN "priceAUD" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "lessons" ADD COLUMN "description" TEXT;

-- CreateTable
CREATE TABLE "attachments" (
    "id" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "courseId" TEXT,
    "lessonId" TEXT,

    CONSTRAINT "attachments_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attachments" ADD CONSTRAINT "attachments_lessonId_fkey" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE CASCADE;
